### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by hoenirvili** [p-e-w/finalterm#411]
``` vala
/tmp/yaourt-tmp-hoenir/aur-finalterm-git/src/finalterm-git/src/TerminalView.vala:229.44-229.48: error: direction of parameter `x' is incompatible with the target delegate
            text_menu.menu.popup(null, null, (menu, out x, out y, out push_in) => {
                                                    ^^^^^
/tmp/yaourt-tmp-hoenir/aur-finalterm-git/src/finalterm-git/src/TerminalView.vala:229.51-229.55: error: direction of parameter `y' is incompatible with the target delegate
            text_menu.menu.popup(null, null, (menu, out x, out y, out push_in) => {

```

**Comment by CJD14** [comment]
check this fix from issue #408 
https://github.com/joshslark/finalterm/commit/04697ea8632feb691238000c856f89f60cc0a612

I had the same issue, must have been an update in vala's source dropping the use of out x, out y in that manner. I cant say for sure. What I can say is I was able to successfully build doing the following as stated in the above links.

simply vim src/TerminalView.vala and change line 229 to this:

    text_menu.menu.popup(null, null, (menu, ref x, ref y, out push_in) => {
instead of this:

     text_menu.menu.popup(null, null, (menu, out x, out y, out push_in) => {
just change the out x, out y, not the out push_in, to ref x, ref y, out push_in

**Comment by hoenirvili** [comment]
Good day sir, i will try this right now , thanks for the tip:D

**Comment by hoenirvili** [comment]
Worked like a charm thanks for everything ! Have a good day sir !

**Comment by CJD14** [comment]
I got that too. Which I reported as issue #410 
I was assisted to fix it temporarily by using 

    export CLUTTER_BACKEND=x11
    finalterm

but that doesnt fix the root issue so expect instability. 
still early in development, 
and Gnome 3.16 changed all kinds of things, which in turn broke this sadly.

**Comment by hoenirvili** [comment]
thanks for all,

**Comment by epitron** [comment]
Nice!

This needs to be merged.
